In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import yaml
from pathlib import Path

In [2]:
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

In [ ]:
clean_data_fp = Path(config['games_folder'] + config['games_clean_fp'])

df = pd.read_json(clean_data_fp, orient='records')

df.head()

,name,rating,updated_at,first_release_date,id,game_modes_Battle Royale,game_modes_Co-operative,game_modes_Massively Multiplayer Online (MMO),game_modes_Multiplayer,game_modes_Single player,...,platforms_WonderSwan Color,platforms_Xbox,platforms_Xbox 360,platforms_Xbox One,platforms_Xbox Series X|S,platforms_ZX Spectrum,platforms_Zeebo,platforms_e-Reader / Card-e Reader,platforms_iOS,platforms_visionOS
0,Escape from Tarkov,71.925826,2026-04-22 15:11:51,1.763165e+09,15536,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Brawl Stars,75.180576,2026-04-22 15:11:43,1.544573e+09,55945,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,Operation Serpens,NaN,2026-04-22 15:08:39,1.595376e+09,138890,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,Rewrite - DYH,NaN,2026-04-22 15:08:21,1.596154e+09,142892,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,War Thunder,74.222581,2026-04-22 15:05:40,1.359331e+09,2165,0,1,1,1,1,...,0,0,0,1,1,0,0,0,0,0

In [4]:
#Checking to make sure the id uniquely identifies each row
print("No duplicate IDS") if len(df['id'].unique()) == len(df) else print("Duplicate IDs found")

No duplicate IDS

In [5]:
#Checking to see if duplicate game names exist
print("No duplicate game names") if len(df['name'].unique()) == len(df) else print("Duplicate game names found")

Duplicate game names found

In [6]:
#Get all rows with duplicate game names
duplicate_names_df = df[df.duplicated(subset=['name'], keep=False)].sort_values('name')
duplicate_names_df.head(6)

,name,rating,updated_at,first_release_date,id,game_modes_Battle Royale,game_modes_Co-operative,game_modes_Massively Multiplayer Online (MMO),game_modes_Multiplayer,game_modes_Single player,...,platforms_WonderSwan Color,platforms_Xbox,platforms_Xbox 360,platforms_Xbox One,platforms_Xbox Series X|S,platforms_ZX Spectrum,platforms_Zeebo,platforms_e-Reader / Card-e Reader,platforms_iOS,platforms_visionOS
16918,10-Pin Bowling,NaN,2024-11-14 09:27:27,9.334656e+08,92273,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
16917,10-Pin Bowling,NaN,2024-11-14 09:33:09,4.732992e+08,153453,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
12698,15 Minutes,NaN,2026-02-02 16:52:35,1.761178e+09,355071,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6119,15 Minutes,NaN,2026-04-09 19:38:22,1.767571e+09,395433,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3834,1942,61.392350,2026-04-18 08:37:59,5.031072e+08,272544,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
5234,1942,67.742592,2026-04-13 08:03:19,4.707072e+08,6075,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [9]:
#Find columns where duplicates differ (excluding name, rating, updated_at, id)
exclude_cols = {'name', 'rating', 'updated_at', 'id'}
cols_to_check = [col for col in duplicate_names_df.columns if col not in exclude_cols]

i = 0
for game_name in duplicate_names_df['name'].unique():
    game_group = duplicate_names_df[duplicate_names_df['name'] == game_name]
    differing_cols = []
    for col in cols_to_check:
        if len(game_group[col].unique()) > 1:
            differing_cols.append(col)
    if'first_release_date' not in differing_cols:  # Print every 10th game to avoid too much output
        print(f"{game_name}: {differing_cols}")
    i+=1

Across the Wonderlands: ['game_modes_Multiplayer']
Ben 10: Protector of Earth: ['platforms_Nintendo DS', 'platforms_PlayStation 2', 'platforms_PlayStation Portable', 'platforms_Wii']
Call of Duty 4: Modern Warfare: ['game_modes_Co-operative', 'game_modes_Split screen', 'genres_Simulator', 'platforms_Mac', 'platforms_Nintendo DS', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 3', 'platforms_Xbox 360']
Call of Duty: Black Ops: ['game_modes_Co-operative', 'game_modes_Split screen', 'platforms_Mac', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 3', 'platforms_Wii', 'platforms_Xbox 360']
Call of Duty: World at War: ['game_modes_Co-operative', 'game_modes_Split screen', 'genres_Adventure', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 3', 'platforms_Wii', 'platforms_Xbox 360']
Carmageddon 64: ['game_modes_Split screen', 'genres_Fighting']
Chicken Blaster: ['platforms_Wii']
Cycles of Aylorea: ['game_modes_Multiplayer', 'genres_Adventure', 'genres_Indie', 'platforms_PlayStation 5', 'platforms_Xbox Series X|S']
Disney's Chicken Little: Ace in Action: ['platforms_Nintendo DS', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 2', 'platforms_Wii']
EA Playground: ['game_modes_Split screen', 'genres_Puzzle', 'platforms_Wii']
LEGO Indiana Jones 2: The Adventure Continues: ['platforms_Mac', 'platforms_Nintendo DS', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 3', 'platforms_Wii', 'platforms_Xbox 360']
Madden NFL 23: ['genres_Simulator', 'genres_Strategy', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 4', 'platforms_PlayStation 5', 'platforms_Xbox One', 'platforms_Xbox Series X|S']
Mega Sports: ['platforms_Amiga', 'platforms_Atari ST/STE', 'platforms_Commodore C64/128/MAX', 'platforms_ZX Spectrum']
Need for Speed: Most Wanted: ['game_modes_Split screen', 'platforms_Nintendo GameCube', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 2', 'platforms_Xbox', 'platforms_Xbox 360']
Playman Extreme Running: []
Project Atlas: ['game_modes_Battle Royale', 'game_modes_Massively Multiplayer Online (MMO)', 'game_modes_Single player', 'genres_Fighting', 'genres_Shooter']
Saban's Mighty Morphin Power Rangers: Mega Battle: ['game_modes_Single player', 'platforms_PlayStation 4']
Skylanders: SuperChargers: ['game_modes_Multiplayer', 'game_modes_Split screen', 'genres_Racing', 'platforms_PlayStation 3', 'platforms_PlayStation 4', 'platforms_Xbox 360', 'platforms_Xbox One']
Snap Together: New Challenges: []
Sonic & Sega All-Stars Racing: ['platforms_Mac', 'platforms_Nintendo DS', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 3', 'platforms_Wii']
Teenage Mutant Ninja Turtles: Smash-Up: ['platforms_PlayStation 2', 'platforms_Wii']
Tetris Attack: ['game_modes_Split screen', 'platforms_Game Boy', 'platforms_Super Nintendo Entertainment System']
Traitor: ['genres_Arcade', 'genres_Role-playing (RPG)']
WALL-E: ['platforms_Mac', 'platforms_PC (Microsoft Windows)', 'platforms_PlayStation 2', 'platforms_PlayStation 3', 'platforms_PlayStation Portable', 'platforms_Xbox 360']
WWF WrestleMania 2000: ['platforms_Game Boy Color', 'platforms_Nintendo 64']
White Knight Chronicles II: ['game_modes_Massively Multiplayer Online (MMO)', 'genres_Adventure']
Yoshi: ['genres_Strategy', 'platforms_Family Computer', 'platforms_Game Boy', 'platforms_Nintendo 3DS', 'platforms_Nintendo Entertainment System', 'platforms_Wii', 'platforms_Wii U']