In [20]:
import pandas as pd
import yaml
from pathlib import Path

In [21]:
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

In [22]:
#Read in covers data
covers_fp = Path(config['covers_folder'] + config['covers_fp'])

covers_df = pd.read_json(covers_fp, orient='records')
covers_df

,id,height,width,url
0,-1,-1.0,-1.0,https://encrypted-tbn0.gstatic.com/images?q=tb...
1,518363,896.0,672.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
2,65483,800.0,1260.0,//images.igdb.com/igdb/image/upload/t_thumb/pk...
3,243407,900.0,600.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
4,334179,1600.0,1200.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
...,...,...,...,...
18496,37754,320.0,480.0,//images.igdb.com/igdb/image/upload/t_thumb/xl...
18497,72778,337.0,600.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
18498,174500,800.0,600.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
18499,174508,800.0,600.0,//images.igdb.com/igdb/image/upload/t_thumb/co...
18500,3453,2629.0,1993.0,//images.igdb.com/igdb/image/upload/t_thumb/jr...

In [4]:
config['feature_names_request_params']['unknown_value']

[-1, 'Unknown', 0]

In [5]:
field_names_df = pd.DataFrame([config['feature_names_request_params']['unknown_value']], columns = config['feature_names_request_params']['fields'].split(","))

In [6]:
field_names_df

   id     name  updated_at
0  -1  Unknown           0